steps:
- name: 'gcr.io/k8s-skaffold/pack'
  entrypoint: pack
  args:
  - build
  - asia-northeast1-docker.pkg.dev/android-picture-1816c/sample-python
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - run
  - deploy
  - --image asia-northeast1-docker.pkg.dev/android-picture-1816c/sample-python
  - sample-python
options:
 logging: CLOUD_LOGGING_ONLY